
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const VITE_SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL="https://hgzsyjaovltugazgatna.supabase.co??";
const VITE_SUPABASE_ANON_KEY = import.meta.env.VITE_SUPABASE_ANON="eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhnenN5amFvdmx0dWdhemdhdG5hIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM3MjU3NDUsImV4cCI6MjA1OTMwMTc0NX0._UsAJ-AK9nwH85sIr9R4Avha_60j4_OfY9saTEVSD3s??";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";


export const supabase = createClient<Database>(VITE_SUPABASE_URL, VITE_SUPABASE_ANON_KEY);



// Export these values for components that need them
export const getSupabaseUrl = () => VITE_SUPABASE_URL;
export const getSupabaseAuth = () => supabase.auth;
